### ISSUE TITLE
Header : login url 문제

### ISSUE THREAD

**Issue by Latemarch** [codestates-seb/seb43_main_032#25]
1. Header에서 로그인 버튼을 누르면 /user/login이 아닌 /login 으로 리디렉션 하고 있습니다.
   - /user/login 으로 변경 필요
   
2. 회원가입 기능은 /user/login 페이지에서 컴포넌트의 변화로 사용할 수 있습니다. 
   - 회원가입 페이지를 따로 만들거나, 
     login 버튼만 남겨 회원 가입 또한 /user/login 페이지에서 수행 될 수 있게 선택해야 해야 합니다.

**Comment by hazellee0914** [comment]
확인 감사드리면 바로 수정하겠습니다

**Comment by shdomi8599** [comment]
굿!

**Comment by Latemarch** [comment]
완!
